### ISSUE TITLE
FindUMFPACK.cmake and FindCHOLMOD.cmake unaware of changes in SuiteSparse 4.3.x

### ISSUE THREAD

**Issue by boegel** [FEniCS/dolfin#2]
There have been changes in SuiteSparse 4.3.x that DOLFIN is not aware of, i.e. the location of the `suitesparseconfig` library which now _must_ be linked as well.

I'll try and take a stab at fixing this myself, but I was wondering if anyone has looked into that already, and whether it should be OK to use the latest SuiteSparse 4.4.6 with DOLFIN.

**Comment by blechta** [comment]
This is just a mirror of https://bitbucket.org/fenics-project/dolfin and developers are not following it here.
