### ISSUE TITLE
Regarding undocumented Advection diffusion problem

### ISSUE THREAD

**Issue by bhargava641** [FEniCS/dolfin#3]
https://github.com/FEniCS/dolfin/blob/master/demo/undocumented/advection-diffusion/python/demo_advection-diffusion.py

In this problem when I take  (@ 47th line ) velocity = 0.0 * velocity I am getting an error. Code anyone let me the reason.

**Comment by garth-wells** [comment]
This just a mirror of the Bitbucket pages. Use https://bitbucket.org/fenics-project/dolfin.
