### ISSUE TITLE
anaconda environment .cache directory filling up and never clearing.

### ISSUE THREAD

**Issue by AshleySetter** [FEniCS/dolfin#4]
I've been running fenics in anaconda and have had an issue where dolfin has been saving files to the 
.cache/instant/cache and never clearing them so that they build up to a ridiculous size (16900 files totalling around 350GB). See the attached text file below of the contents of my .cache/instant/cache directory.

[cache_contents.txt](https://github.com/FEniCS/dolfin/files/2198525/cache_contents.txt)

I've resolved this by just removing all these files at the end of my script after I'm done using fenics but it would be good if this issue was not there. In particular for performing many simulations on a supercomputer in parallel these files build up to a ridiculous size and were restricting me from running more simulations as the supercomputer system I use places a limit on the number of files in my directory.

**Comment by garth-wells** [comment]
Run `instant-clean`.
